### ISSUE TITLE
Image sampling question

### ISSUE THREAD

**Issue by willxxy** [yufeiwang63/RL-VLM-F#1]
Hello,

Thank you for the great work. 

I had a question the random sampling of the two two images (σ0, σ1) from buffer I. Would you be able to clarify whether the σ0, σ1 are from the same time step or are they completely random. From my understanding is that they are completely random. If this is true, wouldn't it be more intuitive to sample the last time step images since they are the most representative of whether the task was completed successfully or not? 

Please let me know whether my reasoning is valid. Thank you and congrats again on the cool work.

**Comment by yufeiwang63** [comment]
Hi,

Thanks for your interest in our work.
We sample the two images completely random, i.e., we first randomly sample two trajectories, and then randomly sample two images from these two trajectories.
It should be possible to just sample the last images of two different trajectories for comparison. In this case, I think the reward model would be trained on a narrower distribution of images (i.e., not trained on images from the middle of the trajectory). Therefore, when using it, it might be best to just use the learned reward model at the end of a trajectory to ensure it is in-distribution. In this case, the reward becomes sparse (only provided at the end of the trajectory). It might still work for simple tasks where reward during the trajectory is not important.

**Comment by willxxy** [comment]
Ok thank you for the answer to the question!
