### ISSUE TITLE
Showing The Robot Arms

### ISSUE THREAD

**Issue by artpli** [yufeiwang63/RL-VLM-F#4]
Hi Yufei ~

I found that when training the open-drawer policy with the provided modified metaworld env, the drawer was always opened first but closed later. Then I tested the expert policy function in the original official metaworld env, the drawer can be opened ideally and won't be closed. Have you observed this phenomenon before?

Then I want to debug with the simulated robot arms but not the abstract arm representations, could you please point me to the part of the code that needs to be modified? Sry I am new to the metaworld env, I tried to work it out myself but haven't done yet. Thank you very much!

Best,
Peng

**Comment by artpli** [comment]
Oh, I noticed the parse.py file. lol

**Comment by artpli** [comment]
![open-drawer](https://github.com/user-attachments/assets/b0b3f8c1-c19d-4ff2-809e-367935d767e8)

Hi Yufei, I found that for the `open-drawer-v2` task, the init state of the drawer is opening with your metaworld env, while the drawer is closed with the original metaworld env. Is this the same as your previous setting? Could you please explain a bit why it is set up this way? Thank you so much!

Best,
Peng

**Comment by artpli** [comment]
https://github.com/yufeiwang63/RL-VLM-F/issues/3#issuecomment-2278076045

I thought you init it in this way to make the task easier just as you said in the above comment?

**Comment by yufeiwang63** [comment]
I think the environment (left) looks like what we used in the testing. I just double checked figure 3 in our paper and the vidoes on our website and it does look like the drawer is initally slightly opened. This is interesting -- I don't think I modified anything other than the sawyer gripper position for this environment. 
I think metaworld has undergone many changes, so I am not sure if this is an issue with the version that I used, or if they made any modifications in the later versions.

**Comment by artpli** [comment]
Thank you for your reply ! !
I haven't delved into the codebase to check why the drawer is initially opened yet. But I think this case is still acceptable for testing your proposed method. I just wanted to check if it was caused by any mistake I made in my configuration. lol
Thanks again !!
