### ISSUE TITLE
I can't find the robot arm

### ISSUE THREAD

**Issue by zlm200** [yufeiwang63/RL-VLM-F#5]
Hi Yufei ~

 When I train the open-drawer policy with the provided modified metaworld env,  I want to find the simulated robot arms but not the abstract arm representations.  How do I set it up to show the robot arm like the one you did in the video in the project showcase.

Best,
zhang

**Comment by yufeiwang63** [comment]
You can uncomment this line here: https://github.com/yufeiwang63/RL-VLM-F/blob/main/metaworld/envs/assets_v2/sawyer_xyz/sawyer_drawer.xml#L7
To show the  robot in the scene.

**Comment by zlm200** [comment]
ok, I find it.
