### ISSUE TITLE
something wrong with the results

### ISSUE THREAD

**Issue by zlm200** [yufeiwang63/RL-VLM-F#6]
when I trained, I found that the outcome was not very good, for example the task of opening the drawer turned out to be the opposite, and the training did not complete the task of opening the drawer many times. The code runs as follows,I wonder if there is any problem?

(rlvlmf) zlm@zlm-MS-7C82:~/RL-VLM-F-main$ HF_ENDPOINT=https://hf-mirror.com python train_PEBBLE.py     env=metaworld_drawer-open-v2     seed=0     exp_name=reproduce     reward=learn_from_preference     vlm_label=1     vlm=gemini_free_form     image_reward=1     reward_batch=40     segment=1     teacher_eps_mistake=0     reward_update=10     num_interact=4000     max_feedback=20000     agent.params.actor_lr=0.0003 agent.params.critic_lr=0.0003 gradient_update=1 activation=tanh num_unsup_steps=9000     num_train_steps=1000000 agent.params.batch_size=512 double_q_critic.params.hidden_dim=256 double_q_critic.params.hidden_depth=3     diag_gaussian_actor.params.hidden_dim=256 diag_gaussian_actor.params.hidden_depth=3      feed_type=0 teacher_beta=-1 teacher_gamma=1  teacher_eps_skip=0 teacher_eps_equal=0     num_eval_episodes=1     cached_label_path=None
workspace: /home/zlm/RL-VLM-F-main/exp/reproduce/metaworld_drawer-open-v2/2024-09-20-15-47-59/vlm_1gemini_free_form_rewardlearn_from_preference_H256_L3_lr0.0003/teacher_b-1_g1_m0_s0_e0/label_smooth_0.0/schedule_0/PEBBLE_init1000_unsup9000_inter4000_maxfeed20000_seg1_acttanh_Rlr0.0003_Rbatch40_Rupdate10_en3_sample0_large_batch10_seed0
[2024-09-20 15:47:59,664][py.warnings][WARNING] - /home/zlm/anaconda3/envs/rlvlmf/lib/python3.9/site-packages/gym/spaces/box.py:128: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")

[2024-09-20 15:47:59,665][py.warnings][WARNING] - /home/zlm/anaconda3/envs/rlvlmf/lib/python3.9/site-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(

| train | E: 3 | S: 1500 | R: -0.4651 | TR: 780.5450 | TF: 0 | LR: 0 | NR: 0 | D: 15.5 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -1.0114 | CLOSS: 0.0943 | TLOSS: 0.6483 | TVAL: 0.0975 | AENT: 2.6511 | BCLOSS: 0.0000
| train | E: 4 | S: 2000 | R: -0.4355 | TR: 400.7375 | TF: 0 | LR: 0 | NR: 0 | D: 14.6 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -2.0249 | CLOSS: 0.1968 | TLOSS: 0.5983 | TVAL: 0.0928 | AENT: 2.4413 | BCLOSS: 0.0000
unsupervised exploration!!
| train | E: 5 | S: 2500 | R: -0.4563 | TR: 576.1622 | TF: 0 | LR: 0 | NR: 0 | D: 15.6 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -3.2531 | CLOSS: 0.2611 | TLOSS: 0.5305 | TVAL: 0.0887 | AENT: 1.9801 | BCLOSS: 0.0000
| train | E: 6 | S: 3000 | R: -0.4199 | TR: 871.7828 | TF: 0 | LR: 0 | NR: 0 | D: 17.4 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -4.6299 | CLOSS: 0.2985 | TLOSS: 0.4795 | TVAL: 0.0849 | AENT: 1.6491 | BCLOSS: 0.0000
unsupervised exploration!!
| train | E: 7 | S: 3500 | R: -0.4288 | TR: 406.4295 | TF: 0 | LR: 0 | NR: 0 | D: 17.1 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -6.1023 | CLOSS: 0.3612 | TLOSS: 0.3911 | TVAL: 0.0814 | AENT: 0.8010 | BCLOSS: 0.0000
| train | E: 8 | S: 4000 | R: -0.4275 | TR: 363.3867 | TF: 0 | LR: 0 | NR: 0 | D: 17.7 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -7.6426 | CLOSS: 0.3998 | TLOSS: 0.3223 | TVAL: 0.0785 | AENT: 0.1076 | BCLOSS: 0.0000
unsupervised exploration!!
| train | E: 9 | S: 4500 | R: -0.4424 | TR: 377.7880 | TF: 0 | LR: 0 | NR: 0 | D: 17.9 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -9.2130 | CLOSS: 0.4157 | TLOSS: 0.2871 | TVAL: 0.0756 | AENT: -0.2058 | BCLOSS: 0.0000
| train | E: 10 | S: 5000 | R: -0.4354 | TR: 356.2714 | TF: 0 | LR: 0 | NR: 0 | D: 17.9 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -10.8049 | CLOSS: 0.4533 | TLOSS: 0.2500 | TVAL: 0.0729 | AENT: -0.5746 | BCLOSS: 0.0000
unsupervised exploration!!
| train | E: 11 | S: 5500 | R: -0.4412 | TR: 355.2946 | TF: 0 | LR: 0 | NR: 0 | D: 14.7 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -12.6017 | CLOSS: 0.5303 | TLOSS: 0.2254 | TVAL: 0.0704 | AENT: -0.7975 | BCLOSS: 0.0000
| train | E: 12 | S: 6000 | R: -0.4365 | TR: 362.2483 | TF: 0 | LR: 0 | NR: 0 | D: 15.3 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -14.7376 | CLOSS: 0.6826 | TLOSS: 0.1997 | TVAL: 0.0678 | AENT: -1.0571 | BCLOSS: 0.0000
unsupervised exploration!!
| train | E: 13 | S: 6500 | R: -0.4299 | TR: 365.8919 | TF: 0 | LR: 0 | NR: 0 | D: 15.4 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -17.2836 | CLOSS: 0.8130 | TLOSS: 0.1054 | TVAL: 0.0657 | AENT: -2.4007 | BCLOSS: 0.0000
| train | E: 14 | S: 7000 | R: -0.4338 | TR: 379.2778 | TF: 0 | LR: 0 | NR: 0 | D: 14.6 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -19.9239 | CLOSS: 0.8869 | TLOSS: 0.0486 | TVAL: 0.0647 | AENT: -3.2496 | BCLOSS: 0.0000
unsupervised exploration!!
| train | E: 15 | S: 7500 | R: -0.4314 | TR: 398.2537 | TF: 0 | LR: 0 | NR: 0 | D: 15.7 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -22.9146 | CLOSS: 1.0177 | TLOSS: 0.0007 | TVAL: 0.0643 | AENT: -3.9885 | BCLOSS: 0.0000
| train | E: 16 | S: 8000 | R: -0.4307 | TR: 369.2562 | TF: 0 | LR: 0 | NR: 0 | D: 17.2 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -25.8765 | CLOSS: 1.1153 | TLOSS: -0.0059 | TVAL: 0.0644 | AENT: -4.0913 | BCLOSS: 0.0000
unsupervised exploration!!
| train | E: 17 | S: 8500 | R: -0.4313 | TR: 373.4250 | TF: 0 | LR: 0 | NR: 0 | D: 16.3 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -28.7985 | CLOSS: 1.2292 | TLOSS: -0.0070 | TVAL: 0.0646 | AENT: -4.1089 | BCLOSS: 0.0000
| train | E: 18 | S: 9000 | R: -0.4286 | TR: 372.6478 | TF: 0 | LR: 0 | NR: 0 | D: 17.9 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -31.9473 | CLOSS: 1.3484 | TLOSS: -0.0245 | TVAL: 0.0653 | AENT: -4.3752 | BCLOSS: 0.0000
unsupervised exploration!!
| train | E: 19 | S: 9500 | R: -0.4308 | TR: 361.6519 | TF: 0 | LR: 0 | NR: 0 | D: 15.5 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -35.0329 | CLOSS: 1.4231 | TLOSS: -0.0390 | TVAL: 0.0667 | AENT: -4.5838 | BCLOSS: 0.0000
| train | E: 20 | S: 10000 | R: -0.4353 | TR: 362.5917 | TF: 0 | LR: 0 | NR: 0 | D: 13.9 s | TD: 00.0 s | BR: -0.0009 | ALOSS: -38.0400 | CLOSS: 1.4926 | TLOSS: -0.0584 | TVAL: 0.0697 | AENT: -4.8386 | BCLOSS: 0.0000
evaluating episode 0
MoviePy - Building file /home/zlm/RL-VLM-F-main/exp/reproduce/metaworld_drawer-open-v2/2024-09-20-15-47-59/vlm_1gemini_free_form_rewardlearn_from_preference_H256_L3_lr0.0003/teacher_b-1_g1_m0_s0_e0/label_smooth_0.0/schedule_0/PEBBLE_init1000_unsup9000_inter4000_maxfeed20000_seg1_acttanh_Rlr0.0003_Rbatch40_Rupdate10_en3_sample0_large_batch10_seed0/eval_gifs/step0010000_episode00_359.42.gif with imageio.
| train | E: 0 | S: 10000 | R: 0.0000 | TR: 0.0000 | TF: 0 | LR: 0 | NR: 0 | D: 00.0 s | TD: 00.0 s | BR: 0.0000 | ALOSS: 0.0000 | CLOSS: 0.0000 | TLOSS: 0.0000 | TVAL: 0.0000 | AENT: 0.0000 | BCLOSS: 0.0000            
| eval  | E: 20 | S: 10000 | R: 359.4239 | TR: 359.4239 | TS: 0.0000
finished unsupervised exploration!!
Killed

**Comment by yufeiwang63** [comment]
Hi,

It looks like you only trained for 10000 environment steps. I think you need to train for longer for the reward/policy to work. You can refer to figure 4 in our paper to get a sense of how many environment steps are needed for the training to take effect.
