### ISSUE TITLE
Unstable fluctuations in learning curves during reproduction

### ISSUE THREAD

**Issue by twoongg** [yufeiwang63/RL-VLM-F#7]
Hi @yufeiwang63,

First of all, thank you for sharing your awesome work!

I've been attempted to reproduce the results from your paper, but I've encountered some discrepancies in the learning curves.
while reproducing the MetaWorld tasks (Open Drawer, Soccer, and Sweep Into), my learning curves exhibit significant fluctuations, unlike the smoother curves presented in the paper.

Could you share the detail or codes used for smoothing?
If possible, could you provide the logs or data used to generate the learning curves reported in the paper?

**Comment by yufeiwang63** [comment]
Hi,

Thanks for your interest in our work! 
We smooth the curves as mentioned here: https://github.com/yufeiwang63/RL-VLM-F/issues/3#issuecomment-2278443301.

I can dig into the codebase for the plotting code.

Also, when reproducing, are you using our cached labels, or re-generating them on the fly? Note that the cached labels are much fewer than those if you generate online, which might leads to more instable results.

**Comment by twoongg** [comment]
Thanks for your prompt response!

Actually I'm first reproducing results with GT preferences and then plan to attempt learning with VLM feedback.
